export const experiences = [
  { id: 1, year: "1998", title: "Esperienza 1998", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 2, year: "2000", title: "Esperienza 2000", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 3, year: "2002", title: "Esperienza 2002", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 4, year: "2004", title: "Esperienza 2004", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 5, year: "2006", title: "Esperienza 2006", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 6, year: "2008", title: "Esperienza 2008", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 7, year: "2010", title: "Esperienza 2010", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 8, year: "2012", title: "Esperienza 2012", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 9, year: "2014", title: "Esperienza 2014", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 10, year: "2016", title: "Esperienza 2016", company: "Azienda", description: "Descrizione da definire...", skills: ["Skill"] },
  { id: 11, year: "2018", title: "Ruby on Rails Developer", company: "Agency", description: "Sviluppo MVC e database PostgreSQL.", skills: ["Ruby", "Rails"] },
  { id: 12, year: "2020", title: "Mobile App Developer", company: "Tech Sol.", description: "App ibride con Ionic e Angular.", skills: ["Ionic", "Angular"] },
  { id: 13, year: "2022", title: "Frontend Animator", company: "Studio", description: "Animazioni con Svelte e GSAP.", skills: ["Svelte", "GSAP"] },
  { id: 14, year: "2024", title: "React Specialist", company: "Curriculum", description: "Mastering React e Next.js.", skills: ["React", "Next.js"] },
  { id: 15, year: "2026", title: "Senior Engineer", company: "Future", description: "Progetti futuri e innovazione.", skills: ["Three.js", "AI"] },
    id: 15,
    year: "2026",
    title: "React Specialist",
    company: "AgileOnTheWeb",
    description: "Mastering React 19, Server Components e Next.js App Router.",
    fullDescription: "Responsabile dell'architettura frontend per una piattaforma SaaS ad alto traffico. L'implementazione di Next.js 14 con il nuovo App Router ha permesso di ottimizzare i Core Web Vitals, portando il LCP sotto i 1.2 secondi. Ho gestito la migrazione di una complessa dashboard da client-side rendering a Server Components, riducendo drasticamente il JavaScript inviato al browser. Abbiamo inoltre integrato un sistema di design atomico utilizzando Tailwind CSS per garantire coerenza visiva e velocità di sviluppo tra i diversi team.",
    videoId: "K9XDq270l40",
    projectUrl: "https://nextjs.org/",
    skills: ["React 19", "Next.js", "Tailwind", "TypeScript"]
  },
];